### ISSUE TITLE
Slog not found

### ISSUE THREAD

**Issue by ern2150** [Jacotsu/Mpeg7Dupes#2]
Maybe I’m waaayyy out of practice with C and Makefiles.

I followed slog’s instructions for install, which puts it in /usr/local/lib, and then followed your instructions for release, and it can’t find slog.

So I tried to make sure my system looked in /usr/local/lib, and did some other debugging, but still can’t get your code to recognize slog exists at compile time.

I noticed latest commit on this project at November 2020, and that slog has had a couple of tags/releases since then.  What’s odd is it doesn’t seem like slog had a Makefile back then, but that might not be odd if people are used to writing the commands to “install” it themselves when needed.

Anyway if I’m missing something obvious please let me know.
I’m really excited to get this running, because I think it’s very silly ffmpeg doesn’t already have this functionality.
I really want to use the signature filter on a list of files, especially since going file-by-file often results in seg faults on my system.

Thanks for any help

**Comment by Jacotsu** [comment]
Compile time or link time?
try running this `gcc -v -Wl,-v -o test.elf build/*.o -std=c11 -fopenmp -lslog -lpthread -lm -lavcodec -lavfilter` and paste the output here

**Comment by ern2150** [comment]
This is from a raspberry pi, but I also had the same general error on WSL running Ubuntu (let me know if you want the same debug command run there)...
```
$ gcc -v -Wl,-v -o test.elf build/*.o -std=c11 -fopenmp -lslog -lpthread -lm -lavcodec -lavfilter
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/6/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 6.3.0-18+rpi1+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1+deb9u1) 
COMPILER_PATH=/usr/lib/gcc/arm-linux-gnueabihf/6/:/usr/lib/gcc/arm-linux-gnueabihf/6/:/usr/lib/gcc/arm-linux-gnueabihf/:/usr/lib/gcc/arm-linux-gnueabihf/6/:/usr/lib/gcc/arm-linux-gnueabihf/
LIBRARY_PATH=/usr/lib/gcc/arm-linux-gnueabihf/6/:/usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/:/usr/lib/gcc/arm-linux-gnueabihf/6/../../../:/lib/arm-linux-gnueabihf/:/lib/:/usr/lib/arm-linux-gnueabihf/:/usr/lib/
Reading specs from /usr/lib/gcc/arm-linux-gnueabihf/6/libgomp.spec
COLLECT_GCC_OPTIONS='-v' '-o' 'test.elf' '-std=c11' '-fopenmp' '-march=armv6' '-mfloat-abi=hard' '-mfpu=vfp' '-mtls-dialect=gnu' '-pthread'
 /usr/lib/gcc/arm-linux-gnueabihf/6/collect2 -plugin /usr/lib/gcc/arm-linux-gnueabihf/6/liblto_plugin.so -plugin-opt=/usr/lib/gcc/arm-linux-gnueabihf/6/lto-wrapper -plugin-opt=-fresolution=/tmp/ccB3nTGu.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lpthread -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --sysroot=/ --build-id --eh-frame-hdr -dynamic-linker /lib/ld-linux-armhf.so.3 -X --hash-style=gnu -m armelf_linux_eabi -o test.elf /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/crt1.o /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/crti.o /usr/lib/gcc/arm-linux-gnueabihf/6/crtbegin.o -L/usr/lib/gcc/arm-linux-gnueabihf/6 -L/usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf -L/usr/lib/gcc/arm-linux-gnueabihf/6/../../.. -L/lib/arm-linux-gnueabihf -L/usr/lib/arm-linux-gnueabihf -v build/ArgumentParsing.o build/main.o build/printers.o build/session.o build/signature_load.o build/signature_lookup.o build/utils.o -lslog -lpthread -lm -lavcodec -lavfilter -lgomp -lgcc --as-needed -lgcc_s --no-as-needed -lpthread -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/arm-linux-gnueabihf/6/crtend.o /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/crtn.o
collect2 version 6.3.0 20170516
/usr/bin/ld -plugin /usr/lib/gcc/arm-linux-gnueabihf/6/liblto_plugin.so -plugin-opt=/usr/lib/gcc/arm-linux-gnueabihf/6/lto-wrapper -plugin-opt=-fresolution=/tmp/ccB3nTGu.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lpthread -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --sysroot=/ --build-id --eh-frame-hdr -dynamic-linker /lib/ld-linux-armhf.so.3 -X --hash-style=gnu -m armelf_linux_eabi -o test.elf /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/crt1.o /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/crti.o /usr/lib/gcc/arm-linux-gnueabihf/6/crtbegin.o -L/usr/lib/gcc/arm-linux-gnueabihf/6 -L/usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf -L/usr/lib/gcc/arm-linux-gnueabihf/6/../../.. -L/lib/arm-linux-gnueabihf -L/usr/lib/arm-linux-gnueabihf -v build/ArgumentParsing.o build/main.o build/printers.o build/session.o build/signature_load.o build/signature_lookup.o build/utils.o -lslog -lpthread -lm -lavcodec -lavfilter -lgomp -lgcc --as-needed -lgcc_s --no-as-needed -lpthread -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/arm-linux-gnueabihf/6/crtend.o /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/crtn.o
GNU ld (GNU Binutils for Raspbian) 2.28
build/main.o: In function `SEGVhandler':
main.c:(.text+0x2a0): undefined reference to `slog'
build/main.o: In function `processFilePair':
main.c:(.text+0x5ac): undefined reference to `slog'
build/main.o: In function `main':
main.c:(.text.startup+0x98): undefined reference to `slog'
main.c:(.text.startup+0x11c): undefined reference to `slog'
main.c:(.text.startup+0x188): undefined reference to `slog'
build/main.o:main.c:(.text.startup+0x1f0): more undefined references to `slog' follow
collect2: error: ld returned 1 exit status

```

**Comment by Jacotsu** [comment]
> LIBRARY_PATH=/usr/lib/gcc/arm-linux-gnueabihf/6/:/usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/:/usr/lib/gcc/arm-linux-gnueabihf/6/../../../:/lib/arm-linux-gnueabihf/:/lib/:/usr/lib/arm-linux-gnueabihf/:/usr/lib/

Your library path is not `/usr/local/lib`, the linker searches for libs in the following paths
```
/usr/lib/gcc/arm-linux-gnueabihf/6/
/usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/
/usr/lib/gcc/arm-linux-gnueabihf/6/../../../:/lib/arm-linux-gnueabihf/
/usr/lib/arm-linux-gnueabihf/
/lib/
/usr/lib/
```
Try reinstalling slog in `/usr/lib`

**Comment by ern2150** [comment]
I made slog install to `/usr/lib`.

I ran `sudo ldconfig`.

When I then ran `ldconfig -p`, it doesn't list `libslog.a`.

I then ran `make release` on Mpeg7Dupes and am (perhaps unsurprisingly) still getting "undefined reference" errors.

**Comment by ern2150** [comment]
Also ran this:
```
$ ld -lslog --verbose
.
.
.
==================================================
attempt to open //usr/local/lib/arm-linux-gnueabihf/libslog.so failed
attempt to open //usr/local/lib/arm-linux-gnueabihf/libslog.a failed
attempt to open //lib/arm-linux-gnueabihf/libslog.so failed
attempt to open //lib/arm-linux-gnueabihf/libslog.a failed
attempt to open //usr/lib/arm-linux-gnueabihf/libslog.so failed
attempt to open //usr/lib/arm-linux-gnueabihf/libslog.a failed
attempt to open //usr/local/lib/libslog.so failed
attempt to open //usr/local/lib/libslog.a succeeded
ld: warning: cannot find entry symbol _start; defaulting to 00010034
```

**Comment by Jacotsu** [comment]
> Also ran this:
> 
> ```
> $ ld -lslog --verbose
> .
> .
> .
> ==================================================
> attempt to open //usr/local/lib/arm-linux-gnueabihf/libslog.so failed
> attempt to open //usr/local/lib/arm-linux-gnueabihf/libslog.a failed
> attempt to open //lib/arm-linux-gnueabihf/libslog.so failed
> attempt to open //lib/arm-linux-gnueabihf/libslog.a failed
> attempt to open //usr/lib/arm-linux-gnueabihf/libslog.so failed
> attempt to open //usr/lib/arm-linux-gnueabihf/libslog.a failed
> attempt to open //usr/local/lib/libslog.so failed
> attempt to open //usr/local/lib/libslog.a succeeded
> ld: warning: cannot find entry symbol _start; defaulting to 00010034
> ```

What happens if you manually copy `libslog.a` into `/usr/lib/arm-linux-gnueabihf/`?

**Comment by ern2150** [comment]
Same results, except `ld` changes the location to that directory.  `make release` still fails on Mpeg7Dupes.

**Comment by ern2150** [comment]
This leads me to believe that the latest version of Slog doesn't get recognized properly, but I'm probably wrong.  I tried to run make/install on the old tag of slog and it didn't change any of the results.

**Comment by Jacotsu** [comment]
> This leads me to believe that the latest version of Slog doesn't get recognized properly, but I'm probably wrong. I tried to run make/install on the old tag of slog and it didn't change any of the results.

It probably has some issues with the path. You can try to force the search path with `-L/path/where/is/libslog.a` and it should work both with gcc and ld

**Comment by ern2150** [comment]
...referring to the path directly like that **while also removing `-lslog`** ~~bizarrely knocks out recognition of the slog.h as it~~ adds a line like this:
```
main.c:(.text.startup+0x3c): undefined reference to `slog_init'
```

If I simply add the `-L` with path then the original error remains the same... perhaps I'm not injecting the direct path thing in the right spot.

**Comment by ern2150** [comment]
Ha, if I replace `-lslog` with a direct file reference to `libslog.a` then the gcc command works...
