### ISSUE TITLE
Segmentation fault almost immediately

### ISSUE THREAD

**Issue by ern2150** [Jacotsu/Mpeg7Dupes#3]
```
$ ./mpeg7Dupes.elf file1 file2 
2021.06.14-09:26:08.66 - [INFO] Logging initialized
                   First signature                              Second signature                 score    time 1 [s]   time 2 [s] whole
2021.06.14-09:26:10.71 - [PANIC] <src/main.c:233> -- Segfault detected, saving session
2021.06.14-09:26:10.72 - [INFO] Saved session file: segfaultedSession.sess
Segmentation fault

$ more segfaultedSession.sess 



```

**Comment by ern2150** [comment]
If nothing else this proves `slog` is working :)

**Comment by Jacotsu** [comment]
Build the debug version and post the output

**Comment by ern2150** [comment]
> Build the debug version and post the output
```
==30498==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
```
...odd, considering:

```
$ make debug
Building debug
make[1]: Entering directory '/mnt/ext/db/git/Mpeg7Dupes'
Linking
cc -g3 -o bin/mpeg7DupesDebug.elf build/signature_load.o build/main.o build/printers.o build/utils.o build/ArgumentParsing.o build/signature_lookup.o build/session.o -lasan -Wall -Wextra -std=c11 -fopenmp ../slog/lib/libslog.a -lpthread -lm -lavcodec -lavfilter
make[1]: Leaving directory '/mnt/ext/db/git/Mpeg7Dupes'
```

...as well as...
```
$ ldconfig -p | grep "asan"
	libasan.so.3 (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libasan.so.3
```

**Comment by ern2150** [comment]
anyway, if I `export LD_PRELOAD` to the right path, re-build debug, and run again, I get:

```
2021.06.14-10:37:40.20 - [INFO] Logging initialized
                   First signature                              Second signature                 score    time 1 [s]   time 2 [s] whole
2021.06.14-10:37:41.14 - [PANIC] <src/main.c:233> -- Segfault detected, saving session
2021.06.14-10:37:41.14 - [INFO] Saved session file: segfaultedSession.sess
ASAN:DEADLYSIGNAL
Segmentation fault
```

**Comment by Jacotsu** [comment]
> anyway, if I `export LD_PRELOAD` to the right path, re-build debug, and run again, I get:
> 
> ```
> 2021.06.14-10:37:40.20 - [INFO] Logging initialized
>                    First signature                              Second signature                 score    time 1 [s]   time 2 [s] whole
> 2021.06.14-10:37:41.14 - [PANIC] <src/main.c:233> -- Segfault detected, saving session
> 2021.06.14-10:37:41.14 - [INFO] Saved session file: segfaultedSession.sess
> ASAN:DEADLYSIGNAL
> Segmentation fault
> ```

Strange, it doesn't even load the signatures. can you upload them here so i can test on my setup?

**Comment by ern2150** [comment]
Will github take 20MB files lol?

**Comment by ern2150** [comment]
[1620609733.024651.26r65n.480p.mp4.signature.bin.zip](https://github.com/Jacotsu/Mpeg7Dupes/files/6650212/1620609733.024651.26r65n.480p.mp4.signature.bin.zip)

**Comment by ern2150** [comment]
That's just the "left" file, lemme know if you also want the "right".   I'd be willing to hear that a 20MB signature file is too large to begin with :)

**Comment by Jacotsu** [comment]
> [1620609733.024651.26r65n.480p.mp4.signature.bin.zip](https://github.com/Jacotsu/Mpeg7Dupes/files/6650212/1620609733.024651.26r65n.480p.mp4.signature.bin.zip)

ok, just checked. The program crashes during the signature loading because there is a mismatch between the frame times. Can you generate an XML signature an upload it here? So i can verify the binary loader

**Comment by ern2150** [comment]
Ok just so you know I tried three separate files of the same size and they all segfaulted... BUT:

I took a 1000-second segment from two other files of the same size, and the comparison started working.  It’s taking awhile, but it’s working.

I will find a suitable location for at least two of the XML size signatures and provide links here.  They’re usually 200-300MB.

**Comment by ern2150** [comment]
Oh ha, the zip (of the xml) ends up being the same size as the bin... which kinda makes sense :)

**Comment by ern2150** [comment]
this is the xml that goes with 1620609733 ("left")...

https://mega.nz/file/Q4YhVAST#nxga48D2rTbFP6CvyF3matRh7IDSB2r8LF05kqx9vvU

(for some reason github didn't like this compressed xml the first couple of times I tried to upload it, but the other one below worked)

**Comment by ern2150** [comment]
this was the "right" bin:
[1620781065.023010.65r61r.480p.mp4.signature.bin.zip](https://github.com/Jacotsu/Mpeg7Dupes/files/6651396/1620781065.023010.65r61r.480p.mp4.signature.bin.zip)

**Comment by ern2150** [comment]
and the xml that goes with 16207... ("right")
[test.xml.zip](https://github.com/Jacotsu/Mpeg7Dupes/files/6651421/test.xml.zip)

**Comment by ern2150** [comment]
Just fyi in case the xmls don't have these details:
```
Input #0, mpegts, from '16x9/1620609733.024651.26r65n.480p.mp4':
  Duration: 02:46:51.36, start: 118.065000, bitrate: 5328 kb/s
  Program 1 
  Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 163 kb/s
  Stream #0:1[0x101]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 852x480 [SAR 1:1 DAR 71:40], 30 fps, 30 tbr, 90k tbn, 60 tbc
  Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
```

```
Input #0, mpegts, from '16x9/1620781065.023010.65r61r.480p.mp4':
  Duration: 02:30:10.68, start: 106.065000, bitrate: 5328 kb/s
  Program 1 
  Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 162 kb/s
  Stream #0:1[0x101]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 852x480 [SAR 1:1 DAR 71:40], 30 fps, 30 tbr, 90k tbn, 60 tbc
  Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
```

**Comment by ern2150** [comment]
> I took a 1000-second segment from two other files of the same size, and the comparison started working. It’s taking awhile, but it’s working.

Same (positive results) is happening for (much larger/longer) files which I'd transcoded to a lower bitrate than 480p - which makes some sense with the whole "consistent frame times" thing.  Wonder if ffmpeg direct comparison will be as forgiving with those...

**Comment by Jacotsu** [comment]
> > I took a 1000-second segment from two other files of the same size, and the comparison started working. It’s taking awhile, but it’s working.
> 
> Same (positive results) is happening for (much larger/longer) files which I'd transcoded to a lower bitrate than 480p - which makes some sense with the whole "consistent frame times" thing. Wonder if ffmpeg direct comparison will be as forgiving with those...

![image](https://user-images.githubusercontent.com/20172693/122070561-5d8b6f00-cdf6-11eb-92a9-b9e9b88692b3.png)
looks like ffmpeg didn't give a correct media time for the first video segment, other segments seem to have the correct time though

**Comment by ern2150** [comment]
So I have some dumb questions, but I think we can close this issue (and open a new one or start a discussion for my questions)?

Like it's an ffmpeg bug with files with weird timecodes, right?

**Comment by Jacotsu** [comment]
> So I have some dumb questions, but I think we can close this issue (and open a new one or start a discussion for my questions)?
> 
> Like it's an ffmpeg bug with files with weird timecodes, right?

Yeah, apparently for this video segment the start time is wrong. You should check it also for the other files that cause a SEGFAULT. The start media time should always be smaller than the end media time
